version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es-network
    hostname: elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - es-network
    hostname: kibana
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver_opts:
      device: ~/Documents/esdata
      type: none
      o: bind

networks:
  es-network:
    driver: bridge
